version: "3"
services:
  scraper:
    build:
      context: ./pdfdrive
    volumes:
      - ./backend/app:/app
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB_NAME="pdfdrive"
      - MONGO_COLLECTION_NAME="pdfdrive"
  db:
    image: mongodb
    restart: always
    environment:
      # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      # - MONGO_HOST="localhost"
      # - MONGO_PORT=27017
      # - MONGO_DB_NAME="pdfdrive"
      # - MONGO_COLLECTION_NAME="pdfdrive"
      # - MONGO_INITDB_ROOT_USERNAME= "root"
      # - MONGO_INITDB_ROOT_PASSWORD="example"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
