version: "3"
services:
  scraper:
    build:
      context: .
    volumes:
      - ./data:/app__pycache__
    depends_on:
      - db
      - redis_db
    environment:
      - MONGO_URI=mongodb://db:27017
      - MONGO_DATABASE=pdfdrive
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - REDIS_PASSWORD=""
  db:
    image: mongo
  
  redis_db:
    image: redis
    
