version: "3"
services:
  scraper:
    build:
      context: .
    volumes:
      - ./app : ./pdfdrive
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB_NAME="pdfdrive"
      - MONGO_COLLECTION_NAME="pdfdrive"
  db:
    image: mongo
    restart: always
    
